name: CI Pipeline for npm TestNG Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  npm-tests:
    name: Run npm Tests
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version you need

      # Step 3: Install npm dependencies
      - name: Install npm dependencies
        run: npm install

      # Step 4: Run npm tests
      - name: Run npm tests
        run: npm test
